instance_activate_object(obj_mlg);
instance_activate_object(obj_senhalogin);
instance_activate_object(obj_entrarmlg);
instance_activate_object(obj_mlgfechar);
instance_activate_object(obj_mlgdown);
instance_activate_object(obj_mlgvoltar);
instance_activate_object(obj_mlgup);
instance_activate_object(obj_conversa1);
instance_activate_object(obj_conversa2);
instance_activate_object(obj_fechamlg);
instance_deactivate_layer("PC");
obj_mlg.sprite_index = spr_mlgsenhas;
senhaisact = true;